---
title: "Shiny App for Tensor Myeloid Paper"
author: "Brian M. Schilder"
date: "12/5/2018"
output: html_document
---

 
 
 
```{r}
setwd("~/Desktop/Tensor_myeloid")

library(DT)
file <- read.table("supp_tables/SUPPLEMENTARY_TABLE_2.txt", sep="\t", fill=NA, header=T)
datatable(file, class = 'cell-border stripe', filter = 'top', options = list(
   scrollY = 300, autoWidth = T))

 
```

```{r}
library(shiny) 

ui <- fluidPage(
  title = "Examples of DataTables",
  sidebarLayout(
    sidebarPanel(
      conditionalPanel(
        'input.dataset === "t2"',
        helpText("Supplementary Table 2.")
      ),
      conditionalPanel(
        'input.dataset === "t3"',
        helpText("Supplementary Table 3.")
      ),
      conditionalPanel(
        'input.dataset === "t4"',
        helpText("Supplementary Table 4.")
      )
    ),
    mainPanel(
      tabsetPanel(
        id = 'dataset',
        tabPanel("t2", DT::dataTableOutput("t2")),
        tabPanel("t3", DT::dataTableOutput("t3")),
        tabPanel("t4", DT::dataTableOutput("t4"))
      )
    )
  )
)

server <- function(input, output) {
  
  # choose columns to display
  t2 <- read.table("supp_tables/SUPPLEMENTARY_TABLE_2.txt", sep="\t", fill=NA)
  output$t2 <- DT::renderDataTable({
    DT::datatable(t2)
  })
  
  # sorted columns are colored now because CSS are attached to them
  t3 <- read.table("supp_tables/SUPPLEMENTARY_TABLE_3.txt", sep="\t", fill=NA)
  output$t3 <- DT::renderDataTable({
    DT::datatable(t3)
  })
  
  # customize the length drop-down menu; display 5 rows per page by default
  t4 <- read.table("supp_tables/SUPPLEMENTARY_TABLE_4.txt", sep="\t", fill=NA)
  output$t4 <- DT::renderDataTable({
    DT::datatable(t4)
  })
  
}

shinyApp(ui, server)
```
 
